<a href="https://colab.research.google.com/github/res1988/workings/blob/master/xgb_multiclass_sample.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from __future__ import division

import numpy as np
import xgboost as xgb
import pandas as pd

In [165]:
pd.read_csv("https://raw.githubusercontent.com/datasets/dermatology/master/data/dermatology.csv")

erythema  scaling  definite_borders  itching  koebner_phenomenon  \
0           2        2                 0        3                   0   
1           3        3                 3        2                   1   
2           2        1                 2        3                   1   
3           2        2                 2        0                   0   
4           2        3                 2        2                   2   
5           2        3                 2        0                   0   
6           2        1                 0        2                   0   
7           2        2                 3        3                   3   
8           2        2                 1        0                   2   
9           2        2                 1        0                   1   
10          3        3                 2        1                   1   
11          2        2                 0        3                   0   
12          3        3                 1        2                   0   
13          2        3                 3        0                   0   
14          2        2                 3        3                   0   
15          1        1                 0        1                   3   
16          2        2                 1        3                   0   
17          3        3                 3        0                   0   
18          2        1                 3        3                   3   
19          1        1                 0        3                   0   
20          2        1                 1        2                   0   
21          3        2                 2        0                   0   
22          2        2                 0        2                   0   
23          2        2                 2        3                   2   
24          2        0                 0        3                   0   
25          2        1                 1        0                   1   
26          1        1                 0        1                   0   
27          1        2                 2        3                   0   
28          3        2                 2        2                   0   
29          1        1                 2        3                   2   
..        ...      ...               ...      ...                 ...   
336         2        3                 2        1                   0   
337         2        1                 0        0                   0   
338         3        1                 0        1                   0   
339         2        1                 2        2                   2   
340         2        2                 3        0                   0   
341         1        1                 0        2                   0   
342         2        0                 1        2                   0   
343         2        2                 2        0                   0   
344         2        2                 1        0                   0   
345         2        2                 2        1                   1   
346         2        2                 2        1                   0   
347         2        2                 0        1                   0   
348         3        2                 2        0                   0   
349         2        2                 1        0                   0   
350         1        2                 2        2                   0   
351         2        2                 2        3                   2   
352         3        2                 2        3                   2   
353         1        1                 1        2                   0   
354         2        0                 1        2                   0   
355         2        3                 2        3                   2   
356         2        2                 2        2                   2   
357         2        2                 2        0                   1   
358         2        3                 2        1              

In [0]:
data_s = pd.read_csv("https://raw.githubusercontent.com/datasets/dermatology/master/data/dermatology.csv")
sz = data_s.shape
# msk = np.random.rand(len(data)) > 0.7

In [0]:

data_s = np.array(data_s)

train_s = data_s[:int(sz[0] * 0.7), :]
test_s = data_s[int(sz[0] * 0.7):, :]


In [0]:
train_X_s = train_s[:, :33]
train_Y_s = train_s[:, 34] -1

test_X_s = test_s[:, :33]
test_Y_s = test_s[:, 34] -1

xg_train_s = xgb.DMatrix(np.array(train_X), label=np.array(train_Y))
xg_test_s = xgb.DMatrix(np.array(test_X), label=np.array(test_Y))

In [172]:
train_Y_s
# np.array(train_X)
# array([[2., 2., 0., ..., 0., 1., 0.],
#        [3., 3., 3., ..., 0., 1., 0.],
#        [2., 1., 2., ..., 0., 2., 3.],
#        ...,
#        [2., 1., 2., ..., 0., 3., 2.],
#        [3., 1., 2., ..., 0., 2., 2.],
#        [2., 1., 2., ..., 0., 2., 2.]])


array([1., 0., 2., 0., 2., 1., 4., 2., 3., 3., 0., 1., 1., 0., 2., 3., 1.,
       0., 2., 4., 5., 1., 4., 2., 4., 0., 5., 4., 1., 2., 0., 1., 0., 0.,
       3., 1., 2., 1., 2., 0., 1., 3., 0., 1., 4., 2., 3., 5., 1., 2., 2.,
       3., 0., 0., 4., 0., 1., 2., 3., 1., 5., 0., 4., 0., 1., 2., 0., 3.,
       4., 0., 1., 5., 2., 4., 3., 1., 1., 0., 2., 4., 0., 1., 1., 1., 4.,
       0., 0., 2., 0., 3., 1., 1., 4., 0., 2., 3., 1., 4., 0., 5., 1., 4.,
       0., 1., 1., 0., 3., 0., 2., 0., 0., 2., 4., 2., 2., 4., 1., 2., 3.,
       0., 1., 4., 5., 0., 0., 1., 5., 2., 4., 3., 0., 0., 2., 4., 4., 0.,
       3., 1., 2., 0., 1., 0., 0., 2., 2., 2., 1., 4., 3., 1., 1., 0., 0.,
       0., 4., 2., 1., 2., 1., 1., 3., 1., 2., 5., 1., 0., 0., 2., 3., 2.,
       2., 0., 0., 0., 2., 0., 0., 1., 2., 2., 0., 0., 0., 0., 5., 1., 1.,
       1., 1., 0., 2., 2., 2., 0., 0., 1., 2., 1., 1., 1., 4., 4., 4., 4.,
       4., 0., 0., 0., 0., 0., 0., 0., 2., 2., 2., 2., 2., 2., 3., 3., 3.,
       3., 4., 4., 4., 4.

In [0]:
# setup parameters for xgboost
param = {}
# use softmax multi-class classification
param['objective'] = 'multi:softmax'
# scale weight of positive examples
param['eta'] = 0.1
param['max_depth'] = 6
param['silent'] = 1
param['nthread'] = 4
param['num_class'] = 6


In [174]:

watchlist = [(xg_train_s, 'train'), (xg_test_s, 'test')]
num_round = 5
bst = xgb.train(param, xg_train_s, num_round, watchlist)
# get prediction
pred = bst.predict(xg_test_s)
error_rate = np.sum(pred != test_Y_s) / test_Y_s.shape[0]
print('Test error using softmax = {}'.format(error_rate))

[0]	train-merror:0.011719	test-merror:0.127273
[1]	train-merror:0.015625	test-merror:0.127273
[2]	train-merror:0.011719	test-merror:0.109091
[3]	train-merror:0.007812	test-merror:0.081818
[4]	train-merror:0.007812	test-merror:0.090909
Test error using softmax = 0.09090909090909091


In [180]:
# do the same thing again, but output probabilities
param['objective'] = 'multi:softprob'
bst = xgb.train(param, xg_train_s, num_round, watchlist)
# Note: this convention has been changed since xgboost-unity
# get prediction, this is in 1D array, need reshape to (ndata, nclass)
pred_prob = bst.predict(xg_test_s).reshape(test_Y_s.shape[0], 6)
pred_label = np.argmax(pred_prob, axis=1)
error_rate = np.sum(pred_label != test_Y_s) / test_Y_s.shape[0]
print('Test error using softprob = {}'.format(error_rate))

[0]	train-merror:0.011719	test-merror:0.127273
[1]	train-merror:0.015625	test-merror:0.127273
[2]	train-merror:0.011719	test-merror:0.109091
[3]	train-merror:0.007812	test-merror:0.081818
[4]	train-merror:0.007812	test-merror:0.090909
Test error using softprob = 0.09090909090909091


In [96]:
error_rate


0.08076923076923077

In [179]:
len(bst.predict(xg_test_s))

110

In [99]:
import os 

os.system("""
if [ -f dermatology.data ]
then
    echo "use existing data to run multi class classification"
else
    echo "getting data from uci, make sure you are connected to internet"
    wget https://archive.ics.uci.edu/ml/machine-learning-databases/dermatology/dermatology.data
fi
""")

0

In [134]:
from __future__ import division

import numpy as np
import xgboost as xgb

# label need to be 0 to num_class -1
data = np.loadtxt('./dermatology.data', delimiter=',',
        converters={33: lambda x:int(x == '?'), 34: lambda x:int(x) - 1})
sz = data.shape

train = data[:int(sz[0] * 0.7), :]
test = data[int(sz[0] * 0.7):, :]

train_X = train[:, :33]
train_Y = train[:, 34]

test_X = test[:, :33]
test_Y = test[:, 34]

xg_train = xgb.DMatrix(train_X, label=train_Y)
xg_test = xgb.DMatrix(test_X, label=test_Y)
# setup parameters for xgboost
param = {}
# use softmax multi-class classification
param['objective'] = 'multi:softmax'
# scale weight of positive examples
param['eta'] = 0.1
param['max_depth'] = 6
param['silent'] = 1
param['nthread'] = 4
param['num_class'] = 6

watchlist = [(xg_train, 'train'), (xg_test, 'test')]
num_round = 5
bst = xgb.train(param, xg_train, num_round, watchlist)
# get prediction
pred = bst.predict(xg_test)
error_rate = np.sum(pred != test_Y) / test_Y.shape[0]
print('Test error using softmax = {}'.format(error_rate))

# do the same thing again, but output probabilities
param['objective'] = 'multi:softprob'
bst = xgb.train(param, xg_train, num_round, watchlist)
# Note: this convention has been changed since xgboost-unity
# get prediction, this is in 1D array, need reshape to (ndata, nclass)
pred_prob = bst.predict(xg_test).reshape(test_Y.shape[0], 6)
pred_label = np.argmax(pred_prob, axis=1)
error_rate = np.sum(pred_label != test_Y) / test_Y.shape[0]
print('Test error using softprob = {}'.format(error_rate))

[0]	train-merror:0.011719	test-merror:0.127273
[1]	train-merror:0.015625	test-merror:0.127273
[2]	train-merror:0.011719	test-merror:0.109091
[3]	train-merror:0.007812	test-merror:0.081818
[4]	train-merror:0.007812	test-merror:0.090909
Test error using softmax = 0.09090909090909091
[0]	train-merror:0.011719	test-merror:0.127273
[1]	train-merror:0.015625	test-merror:0.127273
[2]	train-merror:0.011719	test-merror:0.109091
[3]	train-merror:0.007812	test-merror:0.081818
[4]	train-merror:0.007812	test-merror:0.090909
Test error using softprob = 0.09090909090909091


/usr/local/lib/python3.6/dist-packages/xgboost/core.py:614: UserWarning: Use subset (sliced data) of np.ndarray is not recommended because it will generate extra copies and increase memory consumption
  "because it will generate extra copies and increase memory consumption")


In [105]:
train_Y

array([1., 0., 2., 0., 2., 1., 4., 2., 3., 3., 0., 1., 1., 0., 2., 3., 1.,
       0., 2., 4., 5., 1., 4., 2., 4., 0., 5., 4., 1., 2., 0., 1., 0., 0.,
       3., 1., 2., 1., 2., 0., 1., 3., 0., 1., 4., 2., 3., 5., 1., 2., 2.,
       3., 0., 0., 4., 0., 1., 2., 3., 1., 5., 0., 4., 0., 1., 2., 0., 3.,
       4., 0., 1., 5., 2., 4., 3., 1., 1., 0., 2., 4., 0., 1., 1., 1., 4.,
       0., 0., 2., 0., 3., 1., 1., 4., 0., 2., 3., 1., 4., 0., 5., 1., 4.,
       0., 1., 1., 0., 3., 0., 2., 0., 0., 2., 4., 2., 2., 4., 1., 2., 3.,
       0., 1., 4., 5., 0., 0., 1., 5., 2., 4., 3., 0., 0., 2., 4., 4., 0.,
       3., 1., 2., 0., 1., 0., 0., 2., 2., 2., 1., 4., 3., 1., 1., 0., 0.,
       0., 4., 2., 1., 2., 1., 1., 3., 1., 2., 5., 1., 0., 0., 2., 3., 2.,
       2., 0., 0., 0., 2., 0., 0., 1., 2., 2., 0., 0., 0., 0., 5., 1., 1.,
       1., 1., 0., 2., 2., 2., 0., 0., 1., 2., 1., 1., 1., 4., 4., 4., 4.,
       4., 0., 0., 0., 0., 0., 0., 0., 2., 2., 2., 2., 2., 2., 3., 3., 3.,
       3., 4., 4., 4., 4.